version: '3.7'

services:
  web:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/srv/time-tracker
      - ./dockerfiles/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7-fpm
    restart: always
    volumes:
      - ./:/srv/time-tracker

  mysql_db:
    image: mysql:5.7.29
    restart: always
    environment:
      MYSQL_DATABASE: timetracker
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: timetracker
    volumes:
      - ./docker/db:/var/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    external_links:
      - mysql_db:db
    ports:
      - 8601:80

  composer:
    image: composer
    volumes:
      - "./:/composer"
    working_dir: /composer
    command: install